name: "try"
type: :function
description: "perform action and catch possible errors"
module: "Exceptions"
returns: [
                :null
                 :error
        ]
line: 132
source: "https://github.com/arturo-lang/arturo/blob/v0.9.83/src/library/Exceptions.nim#L132"
examples: [
                {
                        err: try [
                            ; let's try something dangerous
                            print 10 / 0
                        ]
                        
                        type err
                        ; => :error
                        
                        ; Tips: mixing errors and returned values
                        
                        f: $[][ throw "some error" ]
                        g: $[][ return "hi" ]
                        
                        (genericError = err: <= try -> val: f)?
                            -> print err
                            -> print val
                        ; => Generic Error: some error
                        
                        (genericError = err: <= try -> val: g)?
                            -> print err
                            -> print val
                        ; => hi
                }
        ]
attributes: #[
        verbose: #[
                types: [
                                :logical
                        ]
                description: "print all error messages as usual"
                ]
        ]
arguments: #[
        action: [
                        :block
                         :bytecode
                ]
        ]
related: [
                "Exceptions/throw"
                 "Exceptions/throws?"
                 "Exceptions/arithmeticError"
                 "Exceptions/runtimeError"
        ]